# Generated by Django 3.2.9 on 2021-11-08 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('AN', 'Antiques'), ('BO', 'Books'), ('CL', 'Clothing and Accessories'), ('CO', 'Collectibles'), ('EL', 'Electronics'), ('FO', 'Food'), ('FU', 'Furniture'), ('HG', 'Home and Garden'), ('MU', 'Music'), ('PE', 'Pet Supplies'), ('TH', 'Toys and Hobbies'), ('EV', 'Everything Else')], max_length=2, null=True)),
                ('condition', models.CharField(choices=[('BN', 'Brand New'), ('LN', 'Like New'), ('VG', 'Very Good'), ('GO', 'Good'), ('AC', 'Acceptable')], max_length=2, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.URLField(max_length=256, null=True)),
                ('number_of_bids', models.IntegerField(null=True)),
                ('has_comments', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.auctionlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('auction_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.auctionlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('auction_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.auctionlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
